
#ejemplo del print()
print ("hola mundo desde python")

numero = 10+5
variable_prueba = "Hola Variable"
variablePruebaJoroba = "Camello"#Notación camello porque simula jorobas

#Tipo de dato de la variable
print (type (numero))
print (type (variable_prueba))
print (type (variablePruebaJoroba))

#input texto solicita al usuario datos y retorna un str
edad = input ("Dime tu edad")
edad = int(edad)
print (edad)
print (type(edad))